### ISSUE TITLE
Compatibility Issue with Latest Pinocchio Version and TSID

### ISSUE THREAD

**Issue by lvjonok** [conda-forge/tsid-feedstock#34]
### Comment:

Hello,

I’m encountering an issue with synchronization between the latest version of Pinocchio and TSID. It appears that using the latest TSID version forces Pinocchio to revert to a version below 3.0.0. Could you please provide guidance or a fix to ensure compatibility with the newest Pinocchio release?

Thank you for your assistance!

**Comment by lvjonok** [comment]
@jcarpent Could you help with this issue, please?

**Comment by jcarpent** [comment]
I will make a new release then.
